local root = vim.fn.fnamemodify(debug.getinfo(1, "S").source:sub(2), ":h:h")
package.path = root .. "/test/?.lua;" .. root .. "/lua/?.lua;" .. root .. "/lua/?/init.lua;" .. package.path

local h = require("test_helper")

h.run("setup rejects missing port", function()
   h.reset_plugin()
   local done = h.capture_notify()
   require("opcode").setup({ hostname = "127.0.0.1", command = "alacritty -e opencode --port {port}" })
   h.assert_notify_contains("port", vim.log.levels.ERROR)
   done()
end)

h.run("setup rejects non-number port", function()
   h.reset_plugin()
   local done = h.capture_notify()
   require("opcode").setup({ port = "hello", hostname = "127.0.0.1", command = "alacritty -e opencode --port {port}" })
   h.assert_notify_contains("port", vim.log.levels.ERROR)
   done()
end)

h.run("setup rejects out-of-range port", function()
   h.reset_plugin()
   local done = h.capture_notify()
   require("opcode").setup({ port = 0, hostname = "127.0.0.1", command = "alacritty -e opencode --port {port}" })
   h.assert_notify_contains("port", vim.log.levels.ERROR)
   done()
end)

h.run("setup rejects port above 65535", function()
   h.reset_plugin()
   local done = h.capture_notify()
   require("opcode").setup({ port = 70000, hostname = "127.0.0.1", command = "alacritty -e opencode --port {port}" })
   h.assert_notify_contains("port", vim.log.levels.ERROR)
   done()
end)

h.run("setup rejects missing hostname", function()
   h.reset_plugin()
   local done = h.capture_notify()
   require("opcode").setup({ port = 4096, command = "alacritty -e opencode --port {port}" })
   h.assert_notify_contains("hostname", vim.log.levels.ERROR)
   done()
end)

h.run("setup rejects empty hostname", function()
   h.reset_plugin()
   local done = h.capture_notify()
   require("opcode").setup({ port = 4096, hostname = "", command = "alacritty -e opencode --port {port}" })
   h.assert_notify_contains("hostname", vim.log.levels.ERROR)
   done()
end)

h.run("setup rejects non-string hostname", function()
   h.reset_plugin()
   local done = h.capture_notify()
   require("opcode").setup({ port = 4096, hostname = 123, command = "alacritty -e opencode --port {port}" })
   h.assert_notify_contains("hostname", vim.log.levels.ERROR)
   done()
end)

h.run("setup rejects missing command", function()
   h.reset_plugin()
   local done = h.capture_notify()
   require("opcode").setup({ port = 4096, hostname = "127.0.0.1" })
   h.assert_notify_contains("command", vim.log.levels.ERROR)
   done()
end)

h.run("setup rejects command without {port} placeholder", function()
   h.reset_plugin()
   local done = h.capture_notify()
   require("opcode").setup({ port = 4096, hostname = "127.0.0.1", command = "alacritty -e opencode" })
   h.assert_notify_contains("{port}", vim.log.levels.ERROR)
   done()
end)

h.run("setup rejects non-string command", function()
   h.reset_plugin()
   local done = h.capture_notify()
   require("opcode").setup({ port = 4096, hostname = "127.0.0.1", command = 42 })
   h.assert_notify_contains("command", vim.log.levels.ERROR)
   done()
end)

h.run("setup rejects non-boolean notify", function()
   h.reset_plugin()
   local done = h.capture_notify()
   require("opcode").setup(h.valid_config({ notify = "yes" }))
   h.assert_notify_contains("notify", vim.log.levels.ERROR)
   done()
end)

h.run("setup rejects non-positive max_lines_in_prompt", function()
   h.reset_plugin()
   local done = h.capture_notify()
   require("opcode").setup(h.valid_config({ max_lines_in_prompt = 0 }))
   h.assert_notify_contains("max_lines_in_prompt", vim.log.levels.ERROR)
   done()
end)

h.run("setup rejects non-number max_lines_in_prompt", function()
   h.reset_plugin()
   local done = h.capture_notify()
   require("opcode").setup(h.valid_config({ max_lines_in_prompt = "all" }))
   h.assert_notify_contains("max_lines_in_prompt", vim.log.levels.ERROR)
   done()
end)

h.run("setup accepts valid config without errors", function()
   h.reset_plugin()
   local done = h.capture_notify()
   require("opcode").setup(h.valid_config())
   h.assert_no_notify(vim.log.levels.ERROR)
   done()
end)

h.run("setup applies defaults for optional fields", function()
   h.reset_plugin()
   local done = h.capture_notify()
   require("opcode").setup(h.valid_config())
   h.assert_no_notify(vim.log.levels.ERROR)
   done()
end)

h.run("setup is idempotent — second call is a no-op", function()
   h.reset_plugin()
   require("opcode").setup(h.valid_config())
   local done = h.capture_notify()
   require("opcode").setup(h.valid_config({ port = 9999 }))
   h.assert_no_notify(vim.log.levels.ERROR)
   done()
end)

h.run("public API functions error before setup", function()
   h.reset_plugin()
   local done = h.capture_notify()
   local mod = require("opcode")
   mod.connect()
   mod.list_sessions()
   mod.send_file()
   mod.send_selection()
   mod.send_line()
   local notified = done()
   local setup_errors = 0
   for _, n in ipairs(notified) do
      if n.level == vim.log.levels.ERROR and type(n.msg) == "string" and n.msg:find("setup", 1, true) then
         setup_errors = setup_errors + 1
      end
   end
   assert(setup_errors == 5, string.format("Expected 5 setup errors, got %d", setup_errors))
end)

h.run("setup rejects Neovim version < 0.11", function()
   h.reset_plugin()
   local orig_version = vim.version
   local mock = { cmp = function() return -1 end }
   setmetatable(mock, { __call = function() return { major = 0, minor = 10, patch = 0 } end })
   vim.version = mock
   local done = h.capture_notify()
   require("opcode").setup(h.valid_config())
   vim.version = orig_version
   h.assert_notify_contains("Neovim", vim.log.levels.ERROR)
   done()
end)

h.run("module stubs are requireable", function()
   assert(type(require("opcode.api")) == "table", "opcode.api should be a table")
   assert(type(require("opcode.project")) == "table", "opcode.project should be a table")
   assert(type(require("opcode.format")) == "table", "opcode.format should be a table")
   assert(type(require("opcode.commands")) == "table", "opcode.commands should be a table")
end)

h.exit()
